baseURL = "https://hugo-task-1.netlify.app/"
languageCode = "en-us"
title = "Task #1"
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
    